# === Logging ===
logging.pattern.console="%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level requestId=%X{requestId:-N/A} orgId=%X{orgId:-N/A} %logger{36} - %msg%n

# === Spring AI / OpenAI ===
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini

# === Spring AI / DeepSeek ===
spring.ai.deepseek.api-key=${DEEPSEEK_API_KEY}
spring.ai.deepseek.base-url=https://api.deepseek.com
spring.ai.chat.options.model=deepseek-chat
spring.ai.chat.options.temperature=0.2
spring.ai.chat.options.max-tokens=1200

# === Google ===
google.places.api-key=${GOOGLE_PLACES_API_KEY}
google.places.base-url=https://maps.googleapis.com/maps/api/place
google.places.default-radius-m=20000
google.places.max-results=5
google.places.details-enabled=false

mailersend.api-key=${MAILERSEND_API_KEY}
mailersend.base-url=https://api.mailersend.com/v1
mailersend.from-email=no-reply@easymaintenance.com.br
mailersend.from-name=Easy Maintenance

# === Asaas Checkout (callbacks) ===
asaas.checkout-success-url=https://easy-maintenance-web-production.up.railway.app/checkout/success
asaas.checkout-cancel-url=https://easy-maintenance-web-production.up.railway.app/checkout/cancel
asaas.checkout-expired-url=https://easy-maintenance-web-production.up.railway.app/checkout/exp
asaas.checkout-minutes-to-expire=120

# === Google ===
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY}
aws.region=us-east-2
aws.s3.bucket=easy-maintenance

# === Frontend ===
frontend.reset-password-url=https://app.easymaintenance.com/reset-password
frontend.login-url=https://app.easymaintenance.com/login

# === Access Admin ===
bootstrap.admin.token=${BOOTSTRAP_ADMIN_TOKEN}

# === FIREBASE ===
firebase.service.account=${FIREBASE_SERVICE_ACCOUNT_JSON}




# === Actuator & Metrics ===
management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=easy-maintenance
management.prometheus.metrics.export.enabled=true


#spring.flyway.ignore-migration-patterns="*:ignored"
spring.flyway.validate-on-migrate=false

# === Billing ===
billing.blocking.days-after-due=3
