# ============ DATASOURCE (MySQL Docker) ============
easy.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
easy.datasource.username=${MYSQLUSER}
easy.datasource.password=${MYSQLPASSWORD}
easy.datasource.drive=com.mysql.cj.jdbc.Driver

# ============ JPA/Hibernate ============
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# ============ Flyway ============
# spring.flyway.clean-disabled=false

# ============ asaas (Gateway de pagamento) ============
asaas.api-key=${ASAAS_API_KEY}
asaas.base-url=https://sandbox.asaas.com/api/v3
asaas.checkout-success-url=https://easy-maintenance-web-production.up.railway.app/checkout/success
asaas.checkout-cancel-url=https://easy-maintenance-web-production.up.railway.app/checkout/cancel
asaas.checkout-expired-url=https://easy-maintenance-web-production.up.railway.app/checkout/exp
asaas.checkout-minutes-to-expire=1440
asaas.webhook-token=${WEBHOOK-TOKEN}

# === AWS ===
aws.s3.bucket=easy-maintenance

# === Frontend ===
frontend.reset-password-url=https://easy-maintenance-web-production.up.railway.app/reset-password
frontend.login-url=https://easy-maintenance-web-production.up.railway.app/login