INSERT INTO item_types (name, normalized_name, status) VALUES
                                                           ('LIMPEZA CAIXA DE ESGOTO', 'LIMPEZA CAIXA DE ESGOTO', 'ACTIVE'),
                                                           ('LIMPEZA CAIXA DE GORDURA', 'LIMPEZA CAIXA DE GORDURA', 'ACTIVE'),
                                                           ('LIMPEZA CAIXA DE INSPECAO', 'LIMPEZA CAIXA DE INSPECAO', 'ACTIVE'),
                                                           ('LIMPEZA CAIXA DAGUA', 'LIMPEZA CAIXA DAGUA', 'ACTIVE'),
                                                           ('HIGIENIZACAO CAIXA DAGUA', 'HIGIENIZACAO CAIXA DAGUA', 'ACTIVE'),
                                                           ('MANUTENCAO ELETRICA', 'MANUTENCAO ELETRICA', 'ACTIVE'),
                                                           ('MANUTENCAO HIDRAULICA', 'MANUTENCAO HIDRAULICA', 'ACTIVE'),
                                                           ('MANUTENCAO PREDIAL', 'MANUTENCAO PREDIAL', 'ACTIVE'),
                                                           ('MANUTENCAO PORTAO ELETRONICO', 'MANUTENCAO PORTAO ELETRONICO', 'ACTIVE'),
                                                           ('MANUTENCAO CERCA ELETRICA', 'MANUTENCAO CERCA ELETRICA', 'ACTIVE'),

                                                           ('PINTURA DE FACHADA', 'PINTURA DE FACHADA', 'ACTIVE'),
                                                           ('PINTURA INTERNA', 'PINTURA INTERNA', 'ACTIVE'),
                                                           ('PINTURA EXTERNA', 'PINTURA EXTERNA', 'ACTIVE'),
                                                           ('REPARO DE TELHADO', 'REPARO DE TELHADO', 'ACTIVE'),
                                                           ('REPARO DE CALHA', 'REPARO DE CALHA', 'ACTIVE'),
                                                           ('REPARO DE FORRO', 'REPARO DE FORRO', 'ACTIVE'),
                                                           ('REPARO DE PISO', 'REPARO DE PISO', 'ACTIVE'),
                                                           ('REPARO DE PAREDE', 'REPARO DE PAREDE', 'ACTIVE'),
                                                           ('REPARO DE PORTA', 'REPARO DE PORTA', 'ACTIVE'),
                                                           ('REPARO DE JANELA', 'REPARO DE JANELA', 'ACTIVE'),

                                                           ('INSTALACAO DE ILUMINACAO', 'INSTALACAO DE ILUMINACAO', 'ACTIVE'),
                                                           ('INSTALACAO DE TOMADAS', 'INSTALACAO DE TOMADAS', 'ACTIVE'),
                                                           ('INSTALACAO DE INTERRUPTORES', 'INSTALACAO DE INTERRUPTORES', 'ACTIVE'),
                                                           ('INSTALACAO DE LUMINARIAS', 'INSTALACAO DE LUMINARIAS', 'ACTIVE'),
                                                           ('INSTALACAO DE AR CONDICIONADO', 'INSTALACAO DE AR CONDICIONADO', 'ACTIVE'),
                                                           ('INSTALACAO DE VENTILADOR', 'INSTALACAO DE VENTILADOR', 'ACTIVE'),
                                                           ('INSTALACAO DE CORTINAS', 'INSTALACAO DE CORTINAS', 'ACTIVE'),
                                                           ('INSTALACAO DE PERSIANAS', 'INSTALACAO DE PERSIANAS', 'ACTIVE'),
                                                           ('INSTALACAO DE FECHADURA', 'INSTALACAO DE FECHADURA', 'ACTIVE'),
                                                           ('INSTALACAO DE PORTAO', 'INSTALACAO DE PORTAO', 'ACTIVE'),

                                                           ('TROCA DE LAMPADAS', 'TROCA DE LAMPADAS', 'ACTIVE'),
                                                           ('TROCA DE DISJUNTORES', 'TROCA DE DISJUNTORES', 'ACTIVE'),
                                                           ('TROCA DE FIAÇÃO', 'TROCA DE FIACAO', 'ACTIVE'),
                                                           ('TROCA DE TORNEIRA', 'TROCA DE TORNEIRA', 'ACTIVE'),
                                                           ('TROCA DE REGISTRO', 'TROCA DE REGISTRO', 'ACTIVE'),
                                                           ('TROCA DE VASO SANITARIO', 'TROCA DE VASO SANITARIO', 'ACTIVE'),
                                                           ('TROCA DE CHUVEIRO', 'TROCA DE CHUVEIRO', 'ACTIVE'),
                                                           ('TROCA DE FECHADURA', 'TROCA DE FECHADURA', 'ACTIVE'),
                                                           ('TROCA DE VIDRO', 'TROCA DE VIDRO', 'ACTIVE'),
                                                           ('TROCA DE TELHA', 'TROCA DE TELHA', 'ACTIVE'),

                                                           ('INSPECAO PREDIAL', 'INSPECAO PREDIAL', 'ACTIVE'),
                                                           ('INSPECAO ELETRICA', 'INSPECAO ELETRICA', 'ACTIVE'),
                                                           ('INSPECAO HIDRAULICA', 'INSPECAO HIDRAULICA', 'ACTIVE'),
                                                           ('INSPECAO DE TELHADO', 'INSPECAO DE TELHADO', 'ACTIVE'),
                                                           ('INSPECAO DE CALHAS', 'INSPECAO DE CALHAS', 'ACTIVE'),
                                                           ('INSPECAO DE PORTOES', 'INSPECAO DE PORTOES', 'ACTIVE'),
                                                           ('INSPECAO DE ILUMINACAO', 'INSPECAO DE ILUMINACAO', 'ACTIVE'),
                                                           ('INSPECAO DE FORRO', 'INSPECAO DE FORRO', 'ACTIVE'),
                                                           ('INSPECAO DE PISO', 'INSPECAO DE PISO', 'ACTIVE'),
                                                           ('INSPECAO DE PAREDES', 'INSPECAO DE PAREDES', 'ACTIVE'),

                                                           ('SERVICO DE JARDINAGEM', 'SERVICO DE JARDINAGEM', 'ACTIVE'),
                                                           ('CORTE DE GRAMA', 'CORTE DE GRAMA', 'ACTIVE'),
                                                           ('PODA DE ARVORES', 'PODA DE ARVORES', 'ACTIVE'),
                                                           ('LIMPEZA DE TERRENO', 'LIMPEZA DE TERRENO', 'ACTIVE'),
                                                           ('MANUTENCAO DE JARDIM', 'MANUTENCAO DE JARDIM', 'ACTIVE'),
                                                           ('CONTROLE DE PRAGAS', 'CONTROLE DE PRAGAS', 'ACTIVE'),
                                                           ('DEDETIZACAO', 'DEDETIZACAO', 'ACTIVE'),
                                                           ('DESRATIZACAO', 'DESRATIZACAO', 'ACTIVE'),
                                                           ('DESCUPINIZACAO', 'DESCUPINIZACAO', 'ACTIVE'),
                                                           ('LIMPEZA DE CAIXA DE PASSAGEM', 'LIMPEZA DE CAIXA DE PASSAGEM', 'ACTIVE');
